package graphics.resources;

import com.sun.prism.paint.Color;

import java.util.ListResourceBundle;

public class resource_hu extends ListResourceBundle {
    private static final Object[][] contents = {
            {"language", "Magyar"},
            {"table", "Táblázat"},
            {"draw", "Döntetlen"},
            {"id", "Azonosító"},
            {"name", "Név"},
            {"coordinates", "Koordináták"},
            {"creation date", "Létrehozás dátuma"},
            {"height", "Magasság"},
            {"Passport id", "Útlevél"},
            {"HairColor", "Hajszín"},
            {"nationality", "Állampolgárság"},
            {"Location", "Hely"},
            {"user", "Felhasználó"},
            {"add", "Hozzáadás"},
            {"remove by id", "Azonosító eltávolítása"},
            {"Clear", "Tiszta"},
            {"help", "Segítség"},
            {"Info", "Információ"},
            {"Udate id", "Frissítés Azonosítója"},
            {"Execute script", "Futtassa a szkriptet"},
            {"Add if max", "Adja meg, ha max"},
            {"Remove lower", "Távolítsa el az alsót"},
            {"history", "Történelem"},
            {"Print unique location", "Nyomtasson egyedi helyet"},
            {"Show", "Előadás"},
            {"Sorted by", "Rendezés szerint"},
            {"Search", "Keresés"},
            {"File path to execute", "A végrehajtandó fájl elérési útja"},
            {"What to search", "Mit kell keresni?"},
            {"Exit", "Kijárat"},
            {"Answers", "Válaszok"},
            {"Clear answer", "Tiszta válasz"},
            {"Your login:", "Az Ön bejelentkezése:"},
            {"Default", "Alapértelmezett"},
            {"Hello", "Szia"},
            {"Colleсtion was update", "A gyűjtés frissítésre került"},
            {"Item added to the collection", "Elem hozzáadva a gyűjteményhez"},
            {"The item was removed from the collection", "Az elemet eltávolították a gyűjteményből"},
            {"Items were removed from the collection", "Tételeket eltávolítottak a gyűjteményből"},
            {"PathHelp", "src\\rus\\help_hu"},
            {"Collection type", "Gyűjtemény típusa:"},
            {"Items type:", "Tételek típusa"},
            {"Count of items:", "Tételek száma:"},
            {"The object is updated in the collection", " Az objektum frissítve van a gyűjteményben"},
            {"The element was not added because the value is not the maximum", "Az elem nem került hozzáadásra, mert az érték nem a maximális"},
            {"Unique values of the Location field:", "A Hely mező egyedi értékei"},
            {"Error", "Hiba"},
            {"Welcome", "Üdvözöljük"},
            {"Sign up", "Regisztrálj"},
            {"Log in", "Belépés"},
            {"Back", "Vissza"},
            {"Enter your username and password", "Írja be felhasználónevét és jelszavát"},
            {"password", "Jelszó"},
            {"username", "Felhasználónév"},
            {"Access Error or Not found Id", "Hozzáférési hiba vagy nem található azonosító"},
            {"Invalid username or password", "Érvénytelen felhasználónév vagy jelszó"},
            {"Check the entered data", "Ellenőrizze a bevitt adatokat"},
            {"this username already exists", "Ez a felhasználónév már létezik"},
            {"update", "Frissítés"},
            {"delete", "Töröl"},
            {"Enter your username and password for registration", "Írja be felhasználónevét és jelszavát a regisztrációhoz"},
            {"Username (maximum of 15 characters)", "Felhasználónév (legfeljebb 15 karakter)"},
            {"Password (maximum of 15 characters)", "Jelszó (legfeljebb 15 karakter)"},
            {"backgroundColor", Color.BLACK},

    };
    public Object[][] getContents(){return contents;}
}
