package graphics.resources;

import com.sun.prism.paint.Color;

import java.util.ListResourceBundle;

public class resource_en_IE extends ListResourceBundle {
    private static final Object[][] contents = {
            {"language", "English (Ireland)"},
            {"table", "Table"},
            {"draw", "Draw"},
            {"id", "Id"},
            {"name", "Name"},
            {"coordinates", "Coordinates"},
            {"creation date", "Creation date"},
            {"height", "Height"},
            {"Passport id", "Passport"},
            {"HairColor", "Hair Color"},
            {"nationality", "Nationality"},
            {"Location", "Location"},
            {"user", "User"},
            {"add", "Add"},
            {"remove by id", "Remove id"},
            {"Clear", "Clear"},
            {"help", "Help"},
            {"Info", "Info"},
            {"Udate id", "Update Id"},
            {"Execute script", "Execute script"},
            {"Add if max", "Add if max"},
            {"Remove lower", "Remove lower"},
            {"history", "History"},
            {"Print unique location", "Print unique location"},
            {"Show", "Show"},
            {"Sorted by", "Sorted by"},
            {"Search", "Search"},
            {"File path to execute", "File path to execute"},
            {"What to search", "What to search?"},
            {"Exit", "Exit"},
            {"Answers", "Answers"},
            {"Clear answer", "Clear Ans"},
            {"Your login:", "Your login:"},
            {"Default", "Default"},
            {"Hello", "Hello"},
            {"Colleсtion was update", "Colleсtion was update"},
            {"Item added to the collection", "Item added to the collection"},
            {"The item was removed from the collection", "The item was removed from the collection"},
            {"Items were removed from the collection", "Items were removed from the collection"},
            {"PathHelp", "src\\rus\\help_en"},
            {"Collection type", "Collection type:"},
            {"Items type:", "Items type"},
            {"Count of items:", "Count of items:"},
            {"The object is updated in the collection", "The object is updated in the collection"},
            {"The element was not added because the value is not the maximum", "The element was not added because the value is not the maximum"},
            {"Unique values of the Location field:", "Unique values of the Location field:"},
            {"Error", "Error"},
            {"Welcome", "Welcome"},
            {"Sign up", "Sign up"},
            {"Log in", "Log in"},
            {"Back", "Back"},
            {"Enter your username and password", "Enter your username and password"},
            {"password", "Password"},
            {"username", "Username"},
            {"Access Error or Not found Id", "Access Error or Not found Id"},
            {"Invalid username or password", "Invalid username or password"},
            {"Check the entered data", "Check the entered data"},
            {"this username already exists", "this username already exists"},
            {"update", "Update"},
            {"delete", "Delete"},
            {"Enter your username and password for registration", "Enter your username and password for registration"},
            {"Username (maximum of 15 characters)", "Username (maximum of 15 characters)"},
            {"Password (maximum of 15 characters)", "Password (maximum of 15 characters)"},
            {"backgroundColor", Color.BLACK},
            {"defaultPaperSize", new double[] {210, 297}}
    };
    public Object[][] getContents(){return contents;}
}
