package graphics.resources;

import com.sun.prism.paint.Color;

import java.util.ListResourceBundle;

public class resource extends ListResourceBundle {
    private static final Object[][] contents = {
            {"language", "Русский"},
            {"table", "Таблица"},
            {"draw", "Графический интерфейс"},
            {"id", "id"},
            {"name", "Имя"},
            {"coordinates", "Координаты"},
            {"creation date", "Дата создания"},
            {"height", "рост"},
            {"Passport id", "id пасспорта"},
            {"HairColor", "Цвет Волос"},
            {"nationality", "Национальность"},
            {"Location", "Локация"},
            {"user", "пользователь"},
            {"add", "Добавить"},
            {"remove by id", "Удалить по id"},
            {"Clear", "Очистить"},
            {"help", "Помощь"},
            {"Info", "Информация"},
            {"Udate id", "Обновить по id"},
            {"Execute script", "Выполнить скрипт"},
            {"Add if max", "Добавить если максимум"},
            {"Remove lower", "Удалить если меньше"},
            {"history", "История"},
            {"Print unique location", "Вывести уникальные локации"},
            {"Show", "Показать"},
            {"Sorted by", "Сортировать по"},
            {"Search", "Поиск"},
            {"File path to execute", "Путь до файла для выполнения"},
            {"What to search", "Что искать?"},
            {"Exit", "Выход"},
            {"Answers", "Ответы"},
            {"Clear answer", "Очистить ответы"},
            {"Your login:", "Ваш логин:"},
            {"Default", "По умолчанию"},
            {"backgroundColor", Color.BLACK},
            {"Hello", "Здравствуйте"},
            {"Colleсtion was update", "Коллекция обновлена"},
            {"Item added to the collection", "Элемент добавлен в коллекцию"},
            {"The item was removed from the collection", "Элемент удален из коллекции"},
            {"Items were removed from the collection", "Ваши элементы удалены из коллекции"},
            {"PathHelp", "src\\rus\\help"},
            {"Collection type", "Тип коллекции:"},
            {"Items type:", "Тип объектов коллекции"},
            {"Count of items:", "Количество эелементов:"},
            {"The object is updated in the collection", "Объект обновлен в коллекции"},
            {"The element was not added because the value is not the maximum", "Объект не добавлен в коллекцию, так как поле не максимально"},
            {"Unique values of the Location field:", "Уникальные значения поля Локация:"},
            {"Error", "Ошибка"},
            {"Welcome", "Добро Пожаловать"},
            {"Sign up", "Зарегестрироваться"},
            {"Log in", "Войти"},
            {"Back", "Назад"},
            {"Enter your username and password", "Введите имя пользователя и пароль"},
            {"password", "пароль"},
            {"username", "Логин"},
            {"Access Error or Not found Id", "Ошибка доступа или не найден id"},
            {"Invalid username or password", "Неверное имя пользователя или пароль"},
            {"Check the entered data", "Проверьте введенные данные"},
            {"this username already exists", "пользователь с этим именем уже существует"},
            {"update", "Обновить"},
            {"delete", "Удалить"},
            {"Enter your username and password for registration", "Введите свое имя пользователя и пароль для регистрации"},
            {"Username (maximum of 15 characters)", "Логин (не больше 15 символов)"},
            {"Password (maximum of 15 characters)", "Пароль (не больше 15 символов)"},
            {"defaultPaperSize", new double[] {210, 297}}
    };
    public Object[][] getContents(){return contents;}
}

