package graphics.resources;

import com.sun.prism.paint.Color;

import java.util.ListResourceBundle;

public class resource_cs extends ListResourceBundle {
    private static final Object[][] contents = {
            {"language", "Český"},
            {"table", "Tabulka"},
            {"draw", "Vypracovat"},
            {"id", "Idy"},
            {"name", "Název"},
            {"coordinates", "Souřadnice"},
            {"creation date", "Datum vytvoření"},
            {"height", "Výška"},
            {"Passport id", "Pas"},
            {"HairColor", "Barva vlasů"},
            {"nationality", "Státní příslušnost"},
            {"Location", "Umístění"},
            {"user", "Uživatel"},
            {"add", "Přidat"},
            {"remove by id", "Odebrat id"},
            {"Clear", "Průhledná"},
            {"help", "Pomoc"},
            {"Info", "Informace"},
            {"Udate id", "Aktualizovat ID"},
            {"Execute script", "Spusťte skript"},
            {"Add if max", "Přidat, pokud max"},
            {"Remove lower", "Odstraňte spodní část"},
            {"history", "Dějiny"},
            {"Print unique location", "Tisk jedinečného umístění"},
            {"Show", "Ukázat"},
            {"Sorted by", "Řazeno podle"},
            {"Search", "Vyhledávání"},
            {"File path to execute", "Cesta ke spuštění souboru"},
            {"What to search", "Co hledat?"},
            {"Exit", "Výstup"},
            {"Answers", "Odpovědi"},
            {"Clear answer", "Jasná odpověď"},
            {"Your login:", "Vaše přihlašovací údaje:"},
            {"Default", "Výchozí"},
            {"Hello", "Ahoj"},
            {"Colleсtion was update", "Kolekce byla aktualizována"},
            {"Item added to the collection", "Položka byla přidána do kolekce"},
            {"The item was removed from the collection", "Položka byla odebrána ze sbírky"},
            {"Items were removed from the collection", "Položky byly ze sbírky odstraněny"},
            {"PathHelp", "src\\rus\\help_cs"},
            {"Collection type", "Typ kolekce:"},
            {"Items type:", "Typ položky"},
            {"Count of items:", "Počet položek:"},
            {"The object is updated in the collection", "Objekt je aktualizován v kolekci"},
            {"The element was not added because the value is not the maximum", "Prvek nebyl přidán, protože hodnota není maximální"},
            {"Unique values of the Location field:", "Jedinečné hodnoty pole Umístění:"},
            {"Error", "Chyba"},
            {"Welcome", "Vítejte"},
            {"Sign up", "Zaregistrovat"},
            {"Log in", "Přihlásit se"},
            {"Back", " Zadní"},
            {"Enter your username and password", "Zadejte své uživatelské jméno a heslo"},
            {"password", "Heslo"},
            {"username", "Uživatelské jméno"},
            {"Access Error or Not found Id", "Chyba přístupu nebo nenalezeno Id"},
            {"Invalid username or password", "Neplatné uživatelské jméno nebo heslo"},
            {"Check the entered data", "Zkontrolujte zadaná data"},
            {"this username already exists", "Toto uživatelské jméno již existuje"},
            {"update", "Aktualizace"},
            {"delete", "Vymazat"},
            {"Enter your username and password for registration", "Zadejte své uživatelské jméno a heslo pro registraci"},
            {"Username (maximum of 15 characters)", "Uživatelské jméno (maximálně 15 znaků)"},
            {"Password (maximum of 15 characters)", "Heslo (maximálně 15 znaků)"},
            {"backgroundColor", Color.BLACK},
            {"defaultPaperSize", new double[] {210, 297}}
    };
    public Object[][] getContents(){return contents;}
}
